import type { Session, Screenshot } from "../types/session";

const formatDuration = (sec: number): string => {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}m ${s.toString().padStart(2, "0")}s`;
};

const sessionDurationSec = (session: Session): number => {
  if (session.screenshots.length === 0) return 0;
  const last = session.screenshots[session.screenshots.length - 1];
  // Prefer audio-based duration (most accurate) when the recorder ran.
  const audioBased = last.audioOffset.end ?? last.audioOffset.start;
  if (audioBased > 0) return audioBased;
  // Fallback: wall-clock between first and last capturedAt. Used when
  // mic onboarding hasn't been completed (recorder never started).
  const first = session.screenshots[0];
  const firstMs = new Date(first.capturedAt).getTime();
  const lastMs = new Date(last.capturedAt).getTime();
  if (Number.isFinite(firstMs) && Number.isFinite(lastMs) && lastMs >= firstMs) {
    return Math.round((lastMs - firstMs) / 1000);
  }
  return 0;
};

const friendlyTs = (iso: string): string => {
  const m = iso.match(/^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}:\d{2})/);
  return m ? `${m[1]} ${m[2]}` : iso;
};

const renderContext = (s: Screenshot): string => {
  const lines = [`- App: ${s.metadata.app}`];
  if (s.metadata.activeUrl) lines.push(`- URL: ${s.metadata.activeUrl}`);
  if (s.metadata.window) lines.push(`- Window: ${s.metadata.window}`);
  lines.push(`- Captured at: ${s.capturedAt}`);
  lines.push(`- Display: ${s.metadata.resolution} @ ${s.metadata.scale}`);
  return lines.join("\n");
};

const renderNarration = (s: Screenshot): string => {
  if (s.offline && !s.transcriptSegment) {
    const start = s.audioOffset.start.toFixed(1);
    const end = (s.audioOffset.end ?? s.audioOffset.start).toFixed(1);
    return `> *Transcription unavailable — captured offline. Audio segment available at \`audio-master.webm\` from ${start}s to ${end}s.*`;
  }
  return `> ${s.transcriptSegment}`;
};

const renderScreenshot = (s: Screenshot, folder: string): string => {
  const imgPath = `${folder}/${s.canonicalName}.png`;
  const blocks: string[] = [];
  blocks.push(`## Screenshot ${s.seq} — ${s.canonicalName}`);
  blocks.push("");
  blocks.push(`![${s.canonicalName}](${imgPath})`);
  blocks.push("");
  if (s.caption) {
    blocks.push(`**Caption:** ${s.caption}`);
    blocks.push("");
  }
  blocks.push("**Context:**");
  blocks.push(renderContext(s));
  blocks.push("");
  blocks.push("**Narration:**");
  blocks.push("");
  blocks.push(renderNarration(s));
  return blocks.join("\n");
};

export function renderMarkdown(session: Session): string {
  const folder = session.folder.replace(/\/$/, "");
  const audioPath = `${folder}/${session.audioFile}`;
  const duration = formatDuration(sessionDurationSec(session));

  const parts: string[] = [];
  parts.push(`# VisionPipe session — ${friendlyTs(session.createdAt)}`);
  parts.push("");
  parts.push(`**Session folder:** \`${folder}/\``);
  parts.push(`**Screenshots:** ${session.screenshots.length}`);
  parts.push(`**Duration:** ${duration}`);
  parts.push(`**Audio:** \`${audioPath}\``);
  parts.push("");
  parts.push("---");
  parts.push("");

  for (const s of session.screenshots) {
    parts.push(renderScreenshot(s, folder));
    parts.push("");
    parts.push("---");
    parts.push("");
  }

  if (session.closingNarration.trim()) {
    parts.push("## Closing narration");
    parts.push("");
    parts.push(`> ${session.closingNarration}`);
    parts.push("");
    parts.push("---");
    parts.push("");
  }

  parts.push("*Generated by VisionPipe — `screenshot | llm`*");
  parts.push("");

  return parts.join("\n");
}
